sonar.projectKey=3mcp_BES_2026_1SEM_7U_EQ11
sonar.organization=3mcp

sonar.projectName=BES_2026_1SEM_7U_EQ11
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,.next/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
