export const currentUser = {
  id: "user-1",
  name: "Lucas Mendes",
  username: "@lucasmendes",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  coverImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200&h=400&fit=crop",
  bio: "Apaixonado por esportes e vida saudavel. Corredor amador e ciclista de fim de semana.",
  location: "Sao Paulo, SP",
  eventsAttended: 24,
  friends: 156,
  groupsJoined: 8,
  sports: ["Corrida", "Ciclismo", "Futebol", "Natacao"],
};

export const posts = [
  {
    id: "post-1",
    user: {
      name: "Ana Carolina",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Corrida",
    sportEmoji: "🏃",
    content: "Completei minha primeira meia maratona hoje! 21km em 1h52min. Muito feliz com o resultado! Quem mais vai participar da proxima?",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=600&h=400&fit=crop",
    likes: 48,
    comments: 12,
    shares: 3,
    timestamp: "2h atras",
    liked: false,
  },
  {
    id: "post-2",
    user: {
      name: "Pedro Santos",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Futebol",
    sportEmoji: "⚽",
    content: "Pelada confirmada para sabado! Quem topa? Precisamos de mais 4 jogadores para completar o time.",
    likes: 23,
    comments: 8,
    shares: 1,
    timestamp: "4h atras",
    liked: true,
  },
  {
    id: "post-3",
    user: {
      name: "Marina Costa",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Ciclismo",
    sportEmoji: "🚴",
    content: "Trilha incrivel hoje na Serra da Cantareira! 45km de pura adrenalina. Recomendo demais para quem curte mountain bike.",
    image: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=600&h=400&fit=crop",
    likes: 67,
    comments: 15,
    shares: 7,
    timestamp: "6h atras",
    liked: false,
  },
  {
    id: "post-4",
    user: {
      name: "Roberto Alves",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Volei",
    sportEmoji: "🏐",
    content: "Treino de volei de praia amanha as 7h na Praia de Copacabana! Iniciantes sao bem-vindos. Vamos formar novos times!",
    likes: 34,
    comments: 19,
    shares: 5,
    timestamp: "8h atras",
    liked: false,
  },
  {
    id: "post-5",
    user: {
      name: "Juliana Reis",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Tenis",
    sportEmoji: "🎾",
    content: "Finalmente consegui melhorar meu saque! Depois de 3 meses de treino intenso, estou jogando muito melhor. Nao desistam!",
    likes: 89,
    comments: 22,
    shares: 4,
    timestamp: "12h atras",
    liked: true,
  },
  {
    id: "post-6",
    user: {
      name: "Carlos Eduardo",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    },
    sport: "Natacao",
    sportEmoji: "🏊",
    content: "Novo recorde pessoal nos 100m livre: 58 segundos! Meses de dedicacao valeram a pena. Rumo aos 55s!",
    likes: 112,
    comments: 28,
    shares: 9,
    timestamp: "1d atras",
    liked: false,
  },
];

export const events = [
  {
    id: "event-1",
    title: "Corrida Noturna SP",
    sport: "Corrida",
    sportEmoji: "🏃",
    date: "25 Mar 2026",
    time: "19:00",
    location: "Parque Ibirapuera, SP",
    participants: 45,
    maxParticipants: 50,
    status: "open" as const,
    isOfficial: true,
    joined: false,
  },
  {
    id: "event-2",
    title: "Pelada dos Amigos",
    sport: "Futebol",
    sportEmoji: "⚽",
    date: "22 Mar 2026",
    time: "16:00",
    location: "Quadra Municipal Centro",
    participants: 14,
    maxParticipants: 14,
    status: "full" as const,
    isOfficial: false,
    joined: true,
  },
  {
    id: "event-3",
    title: "Pedal da Serra",
    sport: "Ciclismo",
    sportEmoji: "🚴",
    date: "28 Mar 2026",
    time: "06:00",
    location: "Pico do Jaragua",
    participants: 23,
    maxParticipants: 30,
    status: "open" as const,
    isOfficial: true,
    joined: false,
  },
  {
    id: "event-4",
    title: "Torneio de Volei",
    sport: "Volei",
    sportEmoji: "🏐",
    date: "20 Mar 2026",
    time: "09:00",
    location: "Praia de Copacabana",
    participants: 32,
    maxParticipants: 32,
    status: "happening" as const,
    isOfficial: true,
    joined: true,
  },
  {
    id: "event-5",
    title: "Encontro de Tenis",
    sport: "Tenis",
    sportEmoji: "🎾",
    date: "30 Mar 2026",
    time: "08:00",
    location: "Clube Paulistano",
    participants: 8,
    maxParticipants: 16,
    status: "open" as const,
    isOfficial: false,
    joined: false,
  },
  {
    id: "event-6",
    title: "Travessia Aquatica",
    sport: "Natacao",
    sportEmoji: "🏊",
    date: "5 Abr 2026",
    time: "07:00",
    location: "Praia de Santos",
    participants: 67,
    maxParticipants: 100,
    status: "open" as const,
    isOfficial: true,
    joined: false,
  },
];

export const groups = [
  {
    id: "group-1",
    name: "Corredores de SP",
    sport: "Corrida",
    sportEmoji: "🏃",
    coverImage: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400&h=200&fit=crop",
    members: 2340,
    description: "Grupo para corredores de Sao Paulo. Eventos semanais e dicas de treino!",
  },
  {
    id: "group-2",
    name: "Futebol Amador Brasil",
    sport: "Futebol",
    sportEmoji: "⚽",
    coverImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=200&fit=crop",
    members: 5621,
    description: "A maior comunidade de futebol amador do Brasil. Peladas toda semana!",
  },
  {
    id: "group-3",
    name: "Pedal Urbano",
    sport: "Ciclismo",
    sportEmoji: "🚴",
    coverImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400&h=200&fit=crop",
    members: 1890,
    description: "Ciclismo urbano e cicloativismo. Pedaladas noturnas toda sexta!",
  },
  {
    id: "group-4",
    name: "Volei de Praia RJ",
    sport: "Volei",
    sportEmoji: "🏐",
    coverImage: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&h=200&fit=crop",
    members: 987,
    description: "Jogos de volei nas praias do Rio. Todos os niveis sao bem-vindos!",
  },
];

export const upcomingEvents = events.slice(0, 3);

export const suggestedGroups = groups.slice(0, 2);

export const sportFilters = [
  { value: "all", label: "Todos", emoji: "🏆" },
  { value: "corrida", label: "Corrida", emoji: "🏃" },
  { value: "futebol", label: "Futebol", emoji: "⚽" },
  { value: "ciclismo", label: "Ciclismo", emoji: "🚴" },
  { value: "volei", label: "Volei", emoji: "🏐" },
  { value: "tenis", label: "Tenis", emoji: "🎾" },
  { value: "natacao", label: "Natacao", emoji: "🏊" },
];

export const userActivity = [
  {
    id: "activity-1",
    type: "event",
    title: "Participou da Corrida Noturna SP",
    date: "15 Mar 2026",
  },
  {
    id: "activity-2",
    type: "post",
    title: "Publicou sobre treino de ciclismo",
    date: "14 Mar 2026",
  },
  {
    id: "activity-3",
    type: "event",
    title: "Organizou Pelada dos Amigos",
    date: "10 Mar 2026",
  },
  {
    id: "activity-4",
    type: "group",
    title: "Entrou no grupo Corredores de SP",
    date: "5 Mar 2026",
  },
];

export const friends = [
  {
    id: "friend-1",
    name: "Ana Carolina",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "friend-2",
    name: "Pedro Santos",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "friend-3",
    name: "Marina Costa",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "friend-4",
    name: "Roberto Alves",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "friend-5",
    name: "Juliana Reis",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
  },
];
